import { AppLink as Link } from "../../../../components/app-link";
import { notFound } from "next/navigation";
import { requireChatGPTUser } from "../../../chatgpt-auth";
import { AccountHeading } from "../../../../components/account-shell";
import { MembershipManager } from "../../../../components/membership-manager";
import { StatusBadge } from "../../../../components/site-shell";
import { accountPetDetail } from "../../../../lib/account";

export default async function Mascota({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const user = await requireChatGPTUser(`/cuenta/mascotas/${id}`); const data = await accountPetDetail(user, id); if (!data) notFound(); const pet = data.pet as Record<string, unknown>; const membership = data.membership as Record<string, unknown>; const members = data.members as Array<Record<string, unknown>>; const services = data.services as Array<Record<string, unknown>>; return <div className="container account-container"><AccountHeading eyebrow="PERFIL DE MASCOTA" title={String(pet.name)} copy={`${String(pet.species)} · ${String(pet.breed || "Sin raza indicada")}`} actions={<><Link className="button button--secondary" href="/cuenta">Volver</Link>{(membership.role === "OWNER" || membership.can_create_reservations) && <Link className="button button--primary" href={`/cuenta/reservas/nueva?pet=${id}`}>Hacer reserva</Link>}</>}/>
    <div className="pet-profile-grid"><section className="account-panel pet-identity"><div className="pet-profile-photo">{pet.photo_url ? <img src={String(pet.photo_url)} alt={String(pet.name)}/> : String(pet.name).slice(0, 1)}</div><div><StatusBadge status={String(membership.role)}/><h2>{String(pet.name)}</h2><dl><div><dt>Sexo</dt><dd>{String(pet.sex || "Sin indicar")}</dd></div><div><dt>Edad</dt><dd>{pet.approximate_age ? `${String(pet.approximate_age)} años` : "Sin indicar"}</dd></div><div><dt>Peso</dt><dd>{pet.weight ? `${String(pet.weight)} kg` : "Sin indicar"}</dd></div></dl></div></section><section className="account-panel"><span className="eyebrow">HISTORIAL DE SERVICIOS</span><h2>{services.length} servicios</h2>{services.slice(0, 4).map((service) => <div className="compact-service" key={String(service.id)}><div><code>{String(service.service_number)}</code><strong>{String(service.service_type)}</strong><small>{new Date(String(service.scheduled_entry_at)).toLocaleDateString("es-CO")}</small></div><StatusBadge status={String(service.status)}/></div>)}{!services.length && <p className="muted">Aún no hay servicios registrados.</p>}</section></div>
    <MembershipManager petId={id} members={members as never} canManage={membership.role === "OWNER"}/>
  </div>; }
