import Link from "next/link";
import { listServiceTypes } from "../lib/data";
import { PublicShell,SectionHeader } from "../components/site-shell";

export const dynamic="force-dynamic";
export default async function Home(){const services=await listServiceTypes() as Record<string,unknown>[];return <PublicShell>
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">CLUB DE MASCOTAS · MEDELLÍN</span><h1>Libertad para ellos.<br/><em>Tranquilidad para ti.</em></h1><p>Un espacio pensado para que tu mascota juegue, explore, socialice y disfrute mientras tú tienes la tranquilidad de saber que está en buenas manos.</p><div className="hero-actions"><Link className="button button--primary" href="/reservar">Reservar</Link><Link className="button button--secondary" href="/registro">Registrar mi mascota</Link></div><div className="trust-row"><span><b>01</b> Acompañamiento cercano</span><span><b>02</b> Espacios para explorar</span></div></div><div className="hero-visual" aria-label="Una experiencia de libertad y cuidado para tu mascota"><div className="sun"/><div className="land land--far"/><div className="land land--near"/><div className="hero-note"><small>HOY EN EL CLUB</small><strong>Jugar · explorar · descansar</strong></div><div className="pet-orbit pet-orbit--one">BRUNO</div><div className="pet-orbit pet-orbit--two">LUNA</div></div></div></section>
  <section className="brand-strip"><div className="container"><span>BIENESTAR</span><i>·</i><span>NATURALEZA</span><i>·</i><span>LIBERTAD</span><i>·</i><span>CONFIANZA</span><i>·</i><span>COMUNIDAD</span></div></section>
  <section className="section services-section" id="servicios"><div className="container"><SectionHeader eyebrow="EXPERIENCIAS PET SERENO" title="Cada día, a su ritmo" copy="Servicios pensados alrededor del bienestar, con tiempo para moverse, conectar y descansar."/><div className="service-grid">{services.map((service,index)=><article className="service-card" key={String(service.id)}><span className="service-card__number">0{index+1}</span><div className={`service-card__art service-card__art--${index+1}`}><span>{index===0?"DÍA":index===1?"NOCHE":"CUIDADO"}</span></div><div><h3>{String(service.name)}</h3><p>{String(service.short_description)}</p><small>{String(service.price_reference)}</small><Link href={`/reservar?service=${service.id}`}>Solicitar este servicio <span>→</span></Link></div></article>)}</div></div></section>
  <section className="section experience"><div className="container experience-grid"><div className="experience-visual"><div className="experience-quote">“Que se sienta libre,<br/>pero nunca solo.”</div></div><div><span className="eyebrow">LA EXPERIENCIA PET SERENO</span><h2>Cuidado que se nota.<br/>Calma que se comparte.</h2><p>Creemos que una buena estadía comienza por respetar la personalidad y el ritmo de cada mascota.</p><div className="benefit-list"><div><span>01</span><div><strong>Espacio para ser</strong><p>Movimiento, exploración y momentos de pausa en ambientes amplios.</p></div></div><div><span>02</span><div><strong>Mirada cercana</strong><p>Un equipo atento que conoce a cada mascota por su nombre.</p></div></div><div><span>03</span><div><strong>Información clara</strong><p>Reservas organizadas y una referencia única para cada servicio.</p></div></div></div></div></div></section>
  <section className="section process"><div className="container"><SectionHeader eyebrow="SIMPLE DESDE EL PRINCIPIO" title="De la bienvenida al club"/><div className="process-grid"><div><span>1</span><strong>Registra</strong><p>Cuéntanos quién eres y presenta a tu mascota.</p></div><div><span>2</span><strong>Solicita</strong><p>Elige la experiencia, las fechas y las mascotas.</p></div><div><span>3</span><strong>Confirma</strong><p>Recibe una referencia clara para cada servicio.</p></div></div></div></section>
  <section className="section final-cta"><div className="container final-cta__inner"><div><span className="eyebrow">SU PRÓXIMA AVENTURA</span><h2>Un lugar para disfrutar.<br/>Una decisión para respirar tranquilo.</h2></div><div><Link className="button button--light" href="/reservar">Solicitar una reserva</Link><Link className="text-link text-link--light" href="/contacto">Conocer más sobre Pet Sereno →</Link></div></div></section>
 </PublicShell>}
