"use client";
import { useState } from "react";
import { AppLink as Link } from "./app-link";
import { fetchJson } from "../lib/client-fetch";

const steps=["Tus datos","Tu mascota","Confirmación"];
export function RegistrationForm({ source="WEB" }: { source?: "WEB"|"ADMIN" }) {
  const [step,setStep]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<{customerMatched:boolean}|null>(null);
  const [data,setData]=useState<Record<string,string>>({documentType:"CC",species:"Perro",sex:"",department:"Antioquia"});
  const update=(name:string,value:string)=>setData((current)=>({...current,[name]:value}));
  const next=()=>{ setError(""); const required=step===0?["firstName","lastName","documentNumber","phone","email"]:["petName","species"]; const missing=required.find((key)=>!data[key]?.trim()); if(missing){setError("Completa los campos marcados para continuar.");return;} setStep((s)=>Math.min(s+1,2)); };
  const submit=async()=>{setBusy(true);setError("");try{const body=await fetchJson<{customerMatched:boolean}>("/api/register",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({source,customer:{firstName:data.firstName,lastName:data.lastName,documentType:data.documentType,documentNumber:data.documentNumber,phone:data.phone,email:data.email,address:data.address,city:data.city,department:data.department,emergencyContactName:data.emergencyContactName,emergencyContactPhone:data.emergencyContactPhone},pet:{name:data.petName,species:data.species,breed:data.breed,sex:data.sex,birthDate:data.birthDate,approximateAge:data.approximateAge,weight:data.weight,color:data.color,notes:data.notes}})},"No pudimos completar el registro. Intenta de nuevo.");setResult(body);}catch(e){setError(e instanceof Error?e.message:"No pudimos completar el registro. Intenta de nuevo.");}finally{setBusy(false)}};
  if(result)return <div className="confirmation-card" role="status"><span className="confirmation-card__icon">✓</span><span className="eyebrow">Registro completo</span><h2>¡Qué alegría conocer a {data.petName}!</h2><p>{result.customerMatched?"Encontramos tus datos y asociamos la nueva mascota a tu perfil.":"Tus datos y los de tu mascota quedaron guardados correctamente."}</p><div className="confirmation-actions"><Link className="button button--primary" href={`/reservar?document=${encodeURIComponent(data.documentNumber)}`}>Solicitar una reserva</Link><Link className="button button--secondary" href="/">Volver al inicio</Link></div></div>;
  return <form className="step-form" onSubmit={(e)=>{e.preventDefault();if(step<2)next();else void submit();}} noValidate><ol className="stepper" aria-label="Progreso del formulario">{steps.map((label,index)=><li className={index<=step?"is-active":""} key={label}><span>{index<step?"✓":index+1}</span><small>{label}</small></li>)}</ol>{error&&<div className="alert alert--error" role="alert">{error}</div>}
    {step===0&&<div className="form-panel"><div className="form-panel__heading"><span className="eyebrow">Paso 1 de 3</span><h2>Cuéntanos sobre ti</h2><p>Usaremos estos datos para cuidar la comunicación y evitar registros duplicados.</p></div><div className="form-grid"><Field label="Nombre" name="firstName" value={data.firstName} update={update} required/><Field label="Apellido" name="lastName" value={data.lastName} update={update} required/><SelectField label="Tipo de documento" name="documentType" value={data.documentType} update={update} options={["CC","CE","Pasaporte","NIT"]}/><Field label="Número de documento" name="documentNumber" value={data.documentNumber} update={update} required/><Field label="Celular" name="phone" type="tel" value={data.phone} update={update} required hint="Ej. 300 123 4567"/><Field label="Correo" name="email" type="email" value={data.email} update={update} required/><Field label="Dirección" name="address" value={data.address} update={update}/><Field label="Ciudad" name="city" value={data.city} update={update}/><Field label="Departamento" name="department" value={data.department} update={update}/><Field label="Contacto de emergencia" name="emergencyContactName" value={data.emergencyContactName} update={update}/><Field label="Celular de emergencia" name="emergencyContactPhone" type="tel" value={data.emergencyContactPhone} update={update}/></div></div>}
    {step===1&&<div className="form-panel"><div className="form-panel__heading"><span className="eyebrow">Paso 2 de 3</span><h2>Ahora, tu compañero</h2><p>Solo lo esencial para reconocerlo y preparar su experiencia.</p></div><div className="form-grid"><Field label="Nombre de la mascota" name="petName" value={data.petName} update={update} required/><SelectField label="Especie" name="species" value={data.species} update={update} options={["Perro","Gato","Otra"]}/><Field label="Raza" name="breed" value={data.breed} update={update}/><SelectField label="Sexo" name="sex" value={data.sex} update={update} options={["","Macho","Hembra"]}/><Field label="Fecha de nacimiento" name="birthDate" type="date" value={data.birthDate} update={update}/><Field label="Edad aproximada" name="approximateAge" type="number" value={data.approximateAge} update={update}/><Field label="Peso (kg)" name="weight" type="number" value={data.weight} update={update}/><Field label="Color" name="color" value={data.color} update={update}/><label className="field field--full"><span>Algo que quieras contarnos</span><textarea name="notes" value={data.notes??""} onChange={(e)=>update("notes",e.target.value)} placeholder="Una nota breve sobre tu mascota (opcional)"/></label></div></div>}
    {step===2&&<div className="form-panel review-panel"><div className="form-panel__heading"><span className="eyebrow">Paso 3 de 3</span><h2>Todo listo para comenzar</h2><p>Revisa la información antes de guardar.</p></div><div className="review-grid"><div><span>Propietario</span><strong>{data.firstName} {data.lastName}</strong><p>{data.documentType} {data.documentNumber}<br/>{data.phone}<br/>{data.email}</p></div><div><span>Mascota</span><strong>{data.petName}</strong><p>{data.species}{data.breed?` · ${data.breed}`:""}<br/>{data.sex||"Sexo no indicado"}</p></div></div><p className="privacy-note">Al continuar confirmas que los datos son correctos. En esta fase no recopilamos información médica ni de vacunación.</p></div>}
    <div className="form-actions">{step>0&&<button className="button button--tertiary" type="button" onClick={()=>setStep((s)=>s-1)} disabled={busy}>Atrás</button>}<span/>{step<2?<button className="button button--primary" type="submit">Continuar</button>:<button className="button button--primary" type="submit" disabled={busy}>{busy?"Guardando con cuidado…":"Confirmar registro"}</button>}</div></form>;
}

function Field({label,name,value="",update,type="text",required=false,hint}:{label:string;name:string;value?:string;update:(n:string,v:string)=>void;type?:string;required?:boolean;hint?:string}){return <label className="field"><span>{label}{required&&<b aria-hidden="true"> *</b>}</span><input name={name} type={type} value={value} onChange={(e)=>update(name,e.target.value)} required={required} min={type==="number"?"0":undefined}/>{hint&&<small>{hint}</small>}</label>}
function SelectField({label,name,value="",update,options}:{label:string;name:string;value?:string;update:(n:string,v:string)=>void;options:string[]}){return <label className="field"><span>{label}</span><select name={name} value={value} onChange={(e)=>update(name,e.target.value)}>{options.map((option)=><option value={option} key={option}>{option||"Selecciona"}</option>)}</select></label>}
