"use client";
import { useState } from "react";
import { AppLink as Link } from "./app-link";
import { fetchJson } from "../lib/client-fetch";

type Pet={id:string;name:string;species:string;breed:string}; type ServiceType={id:string;name:string;short_description:string}; type Customer={first_name:string;last_name:string;pets:Pet[]};
export function ReservationForm({serviceTypes,initialDocument="",initialServiceTypeId="",initialCustomer=null}:{serviceTypes:ServiceType[];initialDocument?:string;initialServiceTypeId?:string;initialCustomer?:Customer|null}){
 const selectedService=serviceTypes.some((service)=>service.id===initialServiceTypeId)?initialServiceTypeId:serviceTypes[0]?.id??"";
 const [documentNumber,setDocument]=useState(initialDocument); const [customer,setCustomer]=useState<Customer|null>(initialCustomer); const [petIds,setPetIds]=useState<string[]>([]); const [serviceTypeId,setServiceType]=useState(selectedService); const [start,setStart]=useState(""); const [end,setEnd]=useState(""); const [notes,setNotes]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<{reservationNumber:string}|null>(null);
 const identify=async()=>{const document=documentNumber.trim();if(!document){setError("Escribe tu número de documento.");return;}setBusy(true);setError("");try{const b=await fetchJson<{customer:Customer}>(`/api/customers/find?document=${encodeURIComponent(document)}`,undefined,"No encontramos tu registro.");setCustomer(b.customer);}catch(e){setError(e instanceof Error?e.message:"No encontramos tu registro.");setCustomer(null);}finally{setBusy(false)}};
 const submit=async()=>{if(!petIds.length){setError("Selecciona al menos una mascota.");return;}if(!serviceTypeId){setError("Selecciona un servicio.");return;}if(!start||!end){setError("Selecciona las fechas de ingreso y salida.");return;}if(new Date(end)<=new Date(start)){setError("La salida debe ser posterior al ingreso.");return;}setBusy(true);setError("");try{const b=await fetchJson<{reservationNumber:string}>("/api/reservations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({documentNumber,petIds,serviceTypeId,startDatetime:start,endDatetime:end,notes,source:"WEB"})},"No pudimos enviar tu solicitud.");setResult(b);}catch(e){setError(e instanceof Error?e.message:"No pudimos enviar tu solicitud.");}finally{setBusy(false)}};
 if(result)return <div className="confirmation-card"><span className="confirmation-card__icon">✓</span><span className="eyebrow">Solicitud recibida</span><h2>La aventura ya está en camino</h2><p>Tu reserva <strong>{result.reservationNumber}</strong> quedó pendiente de confirmación. Nuestro equipo revisará la disponibilidad antes de generar el número de servicio de cada mascota.</p><div className="service-reference"><small>Referencia administrativa</small><strong>{result.reservationNumber}</strong></div><Link className="button button--primary" href="/">Volver al inicio</Link></div>;
 return <form className="reservation-card" onSubmit={(event)=>{event.preventDefault();void(customer?submit():identify());}} noValidate>{error&&<div className="alert alert--error" role="alert">{error}</div>}{!customer?<div className="identify-panel"><span className="eyebrow">Primero, encontremos tu familia</span><h2>Ingresa tu documento</h2><p>Así podremos mostrarte las mascotas que ya están registradas.</p><label className="field"><span>Número de documento</span><input value={documentNumber} onChange={(e)=>setDocument(e.target.value)} inputMode="numeric" autoComplete="off"/></label><button className="button button--primary" type="submit" disabled={busy||!documentNumber.trim()}>{busy?"Buscando…":"Continuar"}</button><p className="form-help">¿Aún no tienes registro? <Link href="/registro">Registra tu mascota</Link></p></div>:<div className="form-panel"><div className="form-panel__heading"><span className="eyebrow">Hola, {customer.first_name}</span><h2>¿Qué experiencia necesitan?</h2><p>Selecciona una o varias mascotas. Crearemos un servicio independiente para cada una al confirmar.</p></div><div className="pet-choice-grid">{customer.pets.map((pet)=><label className={`pet-choice ${petIds.includes(pet.id)?"is-selected":""}`} key={pet.id}><input type="checkbox" checked={petIds.includes(pet.id)} onChange={(e)=>setPetIds((ids)=>e.target.checked?(ids.includes(pet.id)?ids:[...ids,pet.id]):ids.filter((id)=>id!==pet.id))}/><span className="pet-avatar">{pet.name.slice(0,1)}</span><strong>{pet.name}</strong><small>{pet.species} · {pet.breed||"Sin raza indicada"}</small></label>)}</div><div className="form-grid"><label className="field field--full"><span>Servicio</span><select value={serviceTypeId} onChange={(e)=>setServiceType(e.target.value)}>{serviceTypes.map((s)=><option value={s.id} key={s.id}>{s.name} — {s.short_description}</option>)}</select></label><label className="field"><span>Ingreso</span><input type="datetime-local" value={start} onChange={(e)=>setStart(e.target.value)}/></label><label className="field"><span>Salida</span><input type="datetime-local" min={start||undefined} value={end} onChange={(e)=>setEnd(e.target.value)}/></label><label className="field field--full"><span>Nota para el equipo</span><textarea value={notes} onChange={(e)=>setNotes(e.target.value)} placeholder="Algo breve que nos ayude a preparar su llegada"/></label></div><div className="form-actions"><button className="button button--tertiary" type="button" onClick={()=>{setCustomer(null);setPetIds([]);setError("")}} disabled={busy}>Cambiar documento</button><button className="button button--primary" type="submit" disabled={busy||!petIds.length||!start||!end}>{busy?"Enviando…":"Solicitar reserva"}</button></div></div>}</form>;
}
