import { AppLink as Link } from "../../../../components/app-link";
import { notFound } from "next/navigation";
import { AdminHeader, StatusBadge } from "../../../../components/admin-shell";
import { AdminOperationForm } from "../../../../components/admin-operation-form";
import { ConfirmButton } from "../../../../components/confirm-button";
import { ServiceStatusActions } from "../../../../components/service-status-actions";
import { adminReservationDetail } from "../../../../lib/account";

export const dynamic = "force-dynamic";
export default async function ReservaDetalle({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const data = await adminReservationDetail(id); if (!data) notFound();
  const reservation = data.reservation as Record<string, unknown>; const pet = (data.pet ?? {}) as Record<string, unknown>; const customer = (data.customer ?? {}) as Record<string, unknown>; const service = data.service as Record<string, unknown> | null; const serviceType = (data.service_type ?? {}) as Record<string, unknown>;
  const authorized = (data.authorized_people ?? []) as Array<Record<string, unknown>>; const members = (data.members ?? []) as Array<Record<string, unknown>>; const history = (data.history ?? []) as Array<Record<string, unknown>>; const operations = (data.operations ?? []) as Array<Record<string, unknown>>; const effectiveStatus = service ? String(service.status) : String(reservation.status);
  return <><AdminHeader eyebrow="OPERACIÓN DE RESERVA" title={String(service?.service_number || reservation.reservation_number)} copy={`${String(pet.name || "Mascotas de la reserva")} · ${String(serviceType.name || "Servicio")}`} action={<Link href="/admin/reservas" className="button button--secondary">Volver</Link>}/>
    <div className="detail-grid"><section className="detail-card"><span className="eyebrow">RESERVA</span><h2>{String(pet.name || "Reserva anterior")}</h2><dl><div><dt>Estado</dt><dd><StatusBadge status={effectiveStatus}/></dd></div><div><dt>Ingreso</dt><dd>{new Date(String(reservation.start_datetime)).toLocaleString("es-CO")}</dd></div><div><dt>Salida</dt><dd>{new Date(String(reservation.end_datetime)).toLocaleString("es-CO")}</dd></div><div><dt>Cliente</dt><dd>{String(customer.first_name || "")} {String(customer.last_name || "")}</dd></div></dl>{reservation.status === "PENDING" && <ConfirmButton id={id}/>} {service && <ServiceStatusActions serviceId={String(service.id)} status={String(service.status)}/>}</section>
    <section className="detail-card"><span className="eyebrow">PERSONAS VINCULADAS</span><h2>Acceso y autorización</h2><div className="admin-people"><h3>Propietarios</h3>{members.filter((m) => m.role === "OWNER").map((m) => <p key={String(m.profile_id)}>{String(m.name)} <small>@{String(m.username)}</small></p>)}<h3>Entrega</h3>{authorized.filter((a) => a.authorization_type === "DROPOFF").map((a) => <p key={`d-${a.profile_id}`}>{String(a.name)} <small>@{String(a.username)}</small></p>)}<h3>Recogida</h3>{authorized.filter((a) => a.authorization_type === "PICKUP").map((a) => <p key={`p-${a.profile_id}`}>{String(a.name)} <small>@{String(a.username)}</small></p>)}</div></section></div>
    {service && <section className="admin-section"><div className="admin-section__heading"><div><span className="eyebrow">VALIDACIÓN PRESENCIAL</span><h2>Códigos temporales</h2></div></div><div className="operation-grid">{service.status === "SCHEDULED" && <AdminOperationForm reservationId={id} operation="DROPOFF"/>}{service.status === "READY_FOR_PICKUP" && <AdminOperationForm reservationId={id} operation="PICKUP"/>}{!["SCHEDULED", "READY_FOR_PICKUP"].includes(String(service.status)) && <p className="muted">No hay una operación con código disponible en el estado actual.</p>}</div></section>}
    <section className="admin-section"><div className="admin-section__heading"><div><span className="eyebrow">AUDITORÍA OPERATIVA</span><h2>Historial</h2></div></div><ol className="status-timeline">{history.map((item) => <li key={String(item.id)}><span/><div><StatusBadge status={String(item.new_status)}/><small>{new Date(String(item.changed_at)).toLocaleString("es-CO")}</small>{Boolean(item.notes) && <p>{String(item.notes)}</p>}</div></li>)}</ol>{operations.length > 0 && <div className="operation-log">{operations.map((item) => <p key={String(item.id)}><strong>{item.operation === "DROPOFF" ? "Entrega" : "Recogida"}</strong> validada por código · {new Date(String(item.occurred_at)).toLocaleString("es-CO")}</p>)}</div>}</section>
  </>;
}
